/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif

#include <stdio.h>
#include <stdlib.h>

#ifdef __cplusplus

class cCharStreamInterface;

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else    /* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif    /* __STDC__ */
#endif    /* ! __cplusplus */

#ifdef __TURBOC__
#pragma warn -rch
#pragma warn -use
#include <io.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;


#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 *     if ( condition_holds )
 *        yyless( 5 );
 *    else
 *        do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
    do \
        { \
        /* Undo effects of setting up yytext. */ \
        *yy_cp = yy_hold_char; \
        yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
        YY_DO_BEFORE_ACTION; /* set up yytext again */ \
        } \
    while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
    {
    cCharStreamInterface* yy_input_file;
    int yy_lineno;          /* input line number */
    char *yy_ch_buf;        /* input buffer */
    char *yy_buf_pos;        /* current position in input buffer */

    /* Size of input buffer in bytes, not including room for EOB
     * characters.
     */
    yy_size_t yy_buf_size;

    /* Number of characters read into yy_ch_buf, not including EOB
     * characters.
     */
    int yy_n_chars;

    /* Whether we "own" the buffer - i.e., we know we created it,
     * and can realloc() it to grow it, and should free() it to
     * delete it.
     */
    int yy_is_our_buffer;

    /* Whether this is an "interactive" input source; if so, and
     * if we're using stdio for input, then we want to use getc()
     * instead of fread(), to make sure we stop fetching input after
     * each newline.
     */
    int yy_is_interactive;

    /* Whether we're considered to be at the beginning of a line.
     * If so, '^' rules will be active on the next match, otherwise
     * not.
     */
    int yy_at_bol;

    /* Whether to try to fill the input buffer when we reach the
     * end of it.
     */
    int yy_fill_buffer;

    int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
    /* When an EOF's been seen but there's still some text to process
     * then we mark the buffer as YY_EOF_PENDING, to indicate that we
     * shouldn't try reading from the input source any more.  We might
     * still have a bunch of tokens to match, though, because of
     * possible backing-up.
     *
     * When we actually see the EOF, we change the status to "new"
     * (via yyrestart()), so that the user can continue scanning by
     * just pointing yyin at a new input file.
     */
#define YY_BUFFER_EOF_PENDING 2
    };


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
    { \
    if ( ! yy_current_buffer ) \
        yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
    yy_current_buffer->yy_is_interactive = is_interactive; \
    }

#define yy_set_bol(at_bol) \
    { \
    if ( ! yy_current_buffer ) \
        yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
    yy_current_buffer->yy_at_bol = at_bol; \
    }

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
    yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
    yy_hold_char = *yy_cp; \
    *yy_cp = '\0'; \
    yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 141
#define YY_END_OF_BUFFER 142
static yyconst short int yy_acclist[738] =
    {   0,
      142,  140,  141,  140,  141,  140,  141,  139,  140,  141,
      140,  141,  140,  141,  137,  140,  141,  138,  140,  141,
      140,  141,  131,  140,  141,  131,  140,  141,  131,  140,
      141,  131,  140,  141,  131,  140,  141,  131,  140,  141,
      131,  140,  141,  131,  140,  141,  131,  140,  141,  131,
      140,  141,  131,  140,  141,  131,  140,  141,  131,  140,
      141,  131,  140,  141,  131,  140,  141,  131,  140,  141,
      131,  140,  141,  131,  140,  141,  131,  140,  141,  131,
      140,  141,  131,  140,  141,  140,  141,  136,  140,  141,
      134,  140,  141,  140,  141,  137,  140,  141,  125,  129,

      129,  126,    1,    2,  130,  131,  131,  131,   63,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,    3,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  105,  131,    9,  131,  131,   74,
      131,   78,  131,  131,  131,  131,  131,  131,  131,  131,
       25,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  135,  132,
      133,  129,  129,  129,  130,  131,   23,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,

      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,    5,  131,  131,  131,  131,
      131,  131,  131,   55,  131,  131,  131,  131,  131,  131,
       18,  131,  111,  131,  131,   22,  131,  131,   81,  131,
      131,  131,  131,  131,  131,  131,  131,   86,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,   11,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,   24,  131,  129,  129,  131,  131,  131,
       26,  131,   64,  131,   51,  131,  131,   65,  131,    7,

      131,  131,   52,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,   10,  131,   49,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,   15,  131,  131,  131,
      131,  131,  131,  131,   79,  131,   57,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      120,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,   21,  131,  131,  131,   61,  131,  131,
       92,  131,  131,  131,  131,  131,  131,  131,  131,  131,
       50,  131,  131,  131,  129,  129,  131,  131,  131,  131,

       14,  131,   12,  131,  131,   46,  131,   27,  131,  131,
      131,  131,  131,  131,  131,  131,   69,  131,  131,  131,
      131,   60,  131,  104,  131,   71,  131,   53,  131,  131,
      131,  131,  131,  131,  131,   75,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,   87,
      131,  131,  131,   56,  131,  131,  131,  131,  131,  131,
      131,  131,  121,  131,  131,  131,  131,   13,  131,  131,
      131,  131,  131,  131,   93,  131,  131,   48,  131,  131,
      131,  131,   40,   97,  131,  131,  131,    4,  131,  129,

      129,  131,   98,  131,   99,  131,  131,  131,  131,  131,
      131,  131,   19,  131,   54,  131,  131,  131,  131,   30,
      131,  131,  131,   38,  131,  131,  131,  108,  131,   32,
      131,  131,  131,  131,  131,  131,  110,  131,  131,   80,
      131,  131,  131,   83,  131,  131,  131,  131,  131,  131,
       35,  131,  131,  131,  131,  131,  116,  131,   17,  131,
       88,  131,  131,   58,  131,   20,  131,  131,   31,  131,
      131,   90,  131,   47,  131,    6,  131,  131,  131,  123,
      131,  131,  131,   45,  131,  131,   91,  131,  131,   95,
      131,  131,   96,  131,  131,  131,  128,  129,  129,  131,

      102,  131,   66,  131,  131,   67,  131,    8,  131,  131,
      101,  131,  131,  103,  131,   70,  131,   72,  131,  131,
      131,  131,  131,  131,   39,  131,  131,  131,  131,  112,
      131,   84,  131,   36,  131,  131,  131,  131,  131,  131,
      115,  131,  131,  131,  131,  131,  131,  131,  131,   43,
      131,  131,  131,  131,   33,  131,  131,  127,  129,   62,
      131,   16,  131,   68,  131,   34,  131,  131,   73,  131,
      131,  131,   77,  131,  131,  131,   82,  131,  113,  131,
      131,  114,  131,   85,  131,   28,  131,  117,  131,  118,
      131,  131,  119,  131,  131,   42,  131,  131,   44,  131,

      131,   59,  131,   29,  131,  131,  131,   76,  131,   41,
      131,  100,  131,   37,  131,  131,  131,  124,  131,   94,
      131,  131,  107,  131,  109,  131,   89,  131,  131,  131,
      131,  131,  122,  131,  131,  106,  131
    } ;

static yyconst short int yy_accept[570] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        4,    6,    8,   11,   13,   15,   18,   21,   23,   26,
       29,   32,   35,   38,   41,   44,   47,   50,   53,   56,
       59,   62,   65,   68,   71,   74,   77,   80,   83,   86,
       88,   91,   94,   96,   99,   99,  100,  100,  101,  102,
      102,  103,  103,  104,  105,  106,  107,  108,  109,  111,
      112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
      122,  124,  125,  126,  127,  128,  129,  130,  131,  132,
      133,  134,  135,  137,  139,  140,  142,  144,  145,  146,
      147,  148,  149,  150,  151,  153,  154,  155,  156,  157,

      158,  159,  160,  161,  162,  163,  164,  165,  166,  167,
      168,  169,  170,  171,  172,  173,  174,  175,  176,  177,
      178,  179,  180,  180,  181,  181,  181,  182,  182,  183,
      184,  185,  186,  187,  189,  190,  191,  192,  193,  194,
      195,  196,  197,  198,  199,  200,  201,  202,  203,  204,
      205,  206,  207,  208,  209,  210,  211,  212,  213,  214,
      215,  216,  218,  219,  220,  221,  222,  223,  224,  226,
      227,  228,  229,  230,  231,  233,  235,  236,  238,  239,
      241,  242,  243,  244,  245,  246,  247,  248,  250,  251,
      252,  253,  254,  255,  256,  257,  258,  259,  260,  261,

      262,  263,  264,  265,  266,  267,  268,  269,  270,  272,
      273,  274,  275,  276,  277,  278,  279,  280,  281,  282,
      283,  284,  286,  287,  288,  289,  290,  291,  293,  295,
      297,  298,  300,  302,  303,  305,  306,  307,  308,  309,
      310,  311,  312,  313,  314,  316,  318,  319,  320,  321,
      322,  323,  324,  325,  326,  327,  329,  330,  331,  332,
      333,  334,  335,  337,  339,  340,  341,  342,  343,  344,
      345,  346,  347,  348,  349,  350,  351,  352,  353,  354,
      355,  356,  357,  358,  359,  360,  361,  363,  364,  365,
      366,  367,  368,  369,  370,  371,  372,  373,  374,  376,

      377,  378,  380,  381,  383,  384,  385,  386,  387,  388,
      389,  390,  391,  393,  394,  395,  396,  397,  398,  399,
      400,  401,  403,  405,  406,  408,  410,  411,  412,  413,
      414,  415,  416,  417,  419,  420,  421,  422,  424,  426,
      428,  430,  431,  432,  433,  434,  435,  436,  438,  439,
      440,  441,  442,  443,  444,  445,  446,  447,  448,  449,
      450,  451,  452,  453,  454,  455,  456,  457,  458,  459,
      460,  462,  463,  464,  466,  467,  468,  469,  470,  471,
      472,  473,  475,  476,  477,  478,  480,  481,  482,  483,
      484,  485,  487,  488,  490,  491,  492,  493,  496,  497,

      498,  500,  501,  502,  503,  505,  507,  508,  509,  510,
      511,  512,  513,  515,  517,  518,  519,  520,  522,  523,
      524,  526,  527,  528,  530,  532,  533,  534,  535,  536,
      537,  539,  540,  542,  543,  544,  546,  547,  548,  549,
      550,  551,  553,  554,  555,  556,  557,  559,  561,  563,
      564,  566,  568,  569,  571,  572,  574,  576,  578,  579,
      580,  582,  583,  584,  586,  587,  589,  590,  592,  593,
      595,  596,  597,  599,  600,  601,  603,  605,  606,  608,
      610,  611,  613,  614,  616,  618,  620,  621,  622,  623,
      624,  625,  627,  628,  629,  630,  632,  634,  636,  637,

      638,  639,  640,  641,  643,  644,  645,  646,  647,  648,
      649,  650,  652,  653,  654,  655,  657,  658,  660,  662,
      664,  666,  668,  669,  671,  672,  673,  675,  676,  677,
      679,  681,  682,  684,  686,  688,  690,  692,  693,  695,
      696,  698,  699,  701,  702,  704,  706,  707,  708,  710,
      712,  714,  716,  717,  718,  720,  722,  723,  725,  727,
      729,  730,  731,  732,  733,  735,  736,  738,  738
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,    1,    1,    5,    6,    1,
        1,    7,    1,    1,    1,    1,    8,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    1,    1,   10,
        1,   11,    1,   12,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
        1,   14,    1,    1,   13,    1,   15,   16,   17,   18,

       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   13,   31,   32,   33,   34,   35,   36,   37,
       38,   39,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[40] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    3,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3
    } ;

static yyconst short int yy_base[579] =
    {   0,
        0,    0,   35,   42,   46,   53,   57,   67,  615,  616,
       40,  591,  616,   59,   67,  616,  616,    0,    0,   55,
       61,   69,   67,   74,   89,  584,   96,  583,  577,   78,
      101,   51,  591,  121,   91,  119,   21,  587,  579,  599,
      616,  616,  105,   92,  124,  616,  604,    0,   52,  119,
      616,  603,  616,  616,    0,    0,  572,  585,  570,  572,
      567,  567,  569,  578,  563,   98,  131,  580,  566,  132,
      559,  564,  559,  556,  570,  123,  562,  111,  558,  555,
      562,  551,    0,    0,  553,  134,    0,  144,  549,  135,
      545,  554,   93,  555,    0,  545,  558,  147,  142,  560,

      164,  537,  154,  545,  149,  158,  543,  549,  543,  543,
      151,  160,  539,  540,  538,  160,  164,  535,  176,  542,
      533,  616,  190,  616,  561,  189,  616,  560,    0,  531,
      543,    0,  526,    0,  539,  530,  527,  536,  528,  538,
      533,  532,  533,  518,  531,  515,  173,  523,  530,  525,
      527,  527,  522,  513,  511,  512,  518,  504,  520,  515,
      518,  513,  512,  501,  181,  506,  494,  494,  507,  500,
      503,  508,  503,  498,    0,    0,  505,    0,  500,    0,
      487,  492,  176,  481,  178,  489,  496,    0,  490,  493,
      478,  161,  477,  483,  193,  477,  479,  487,  184,  191,

      486,  471,  486,  472,  469,  471,  471,  479,    0,  478,
      463,  467,  472,  464,  200,  463,  463,  457,  471,  473,
      461,    0,  457,  459,  453,  452,  459,    0,    0,  462,
      455,    0,    0,  457,    0,  453,  445,  443,  452,  447,
      439,  195,  446,  444,    0,    0,  437,  446,  190,  449,
      441,  448,  432,  449,  435,    0,  201,  431,  433,  427,
      444,  427,    0,    0,  441,  424,  420,  421,  436,  421,
      436,  423,  426,  433,  428,  200,  423,  416,  412,  428,
      411,  418,  409,  420,  419,  420,    0,  403,  416,  405,
      408,  409,  205,  414,  399,  412,  406,  401,    0,  390,

      393,    0,  208,    0,  403,  404,  394,  401,  399,  388,
      397,  383,    0,  383,  396,  383,  379,  397,  378,  393,
      394,    0,    0,  389,    0,    0,  379,  391,  379,  389,
      384,  383,  378,    0,  383,  381,  370,    0,  371,    0,
        0,  379,  377,  367,  376,  359,  372,    0,  362,  207,
      363,  358,  368,  357,  352,  361,  362,  350,  366,  347,
      348,  361,  360,  359,  347,  341,  341,  349,  343,  342,
        0,  351,  335,    0,  349,  346,  350,  347,  330,  341,
      328,    0,  338,  328,  343,  325,  333,  336,  336,  338,
      332,    0,  334,    0,  331,  321,  315,    0,  332,  323,

        0,  312,  326,  326,    0,    0,  314,  323,  306,  313,
      305,  304,    0,    0,  319,  312,  302,    0,  295,  310,
        0,  312,  307,    0,    0,  312,  313,  312,  307,  310,
        0,  297,    0,  305,  303,    0,  295,  301,  286,  285,
      288,    0,  290,  296,  295,  296,    0,    0,    0,  283,
        0,    0,  285,    0,  290,    0,    0,    0,  280,  275,
        0,  288,  286,    0,  278,    0,  279,    0,  284,    0,
      276,  275,    0,  281,  266,    0,    0,  279,    0,    0,
      278,    0,  263,    0,    0,    0,  267,  261,  274,  275,
      265,    0,  273,  266,  269,    0,    0,    0,  249,  267,

      259,  246,  252,    0,  249,  250,  254,  249,  250,  258,
      248,    0,  256,  255,  255,    0,  253,    0,    0,    0,
        0,    0,  238,    0,  241,  250,    0,  227,  228,    0,
        0,  226,    0,    0,    0,    0,    0,  214,    0,  219,
        0,  208,    0,  222,    0,    0,  215,  219,    0,    0,
        0,    0,  221,  195,    0,    0,  199,    0,    0,    0,
      162,  118,  116,   65,    0,   53,    0,  616,  247,  250,
       58,  253,   38,  255,  258,  261,  263,  265
    } ;

static yyconst short int yy_def[579] =
    {   0,
      568,    1,  569,  569,  569,  569,  569,  569,  568,  568,
      570,  571,  568,  572,  568,  568,  568,  573,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  568,
      568,  568,  575,  576,  570,  568,  570,  577,  577,  572,
      568,  572,  568,  568,  578,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,

      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  568,  575,  568,  575,  576,  568,  576,  577,  577,
      577,  578,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,

      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  577,  577,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,

      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  577,  577,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,

      574,  577,  577,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  577,  577,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,

      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  577,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  574,  574,
      574,  574,  574,  574,  574,  574,  574,    0,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568
    } ;

static yyconst short int yy_nxt[656] =
    {   0,
       10,   10,   11,   12,   13,   14,   10,   15,   10,   16,
       17,   18,   19,   10,   20,   21,   22,   23,   24,   25,
       26,   19,   27,   19,   19,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   19,   19,   13,
       55,   40,   46,  118,   16,   17,   13,   41,   40,  119,
       13,   16,   17,   47,   41,   16,   17,   13,   42,   43,
       48,   13,   16,   17,   51,   98,   44,   17,   42,   43,
       57,   13,   52,   53,   54,   62,   44,   17,  130,  131,
      567,   99,   58,   66,  100,   70,   59,   60,   61,   63,
       67,   64,   90,  566,   68,   71,   91,   69,   65,   73,

       92,   74,  127,   77,   72,  128,   93,  124,   75,  110,
       76,   78,  111,   83,   79,   84,   94,   80,  125,   81,
      177,  112,   85,   86,   51,  178,   46,   87,  113,  142,
      143,   95,   52,  565,   96,   97,  102,   47,  159,  103,
      564,  114,  104,  105,  115,  144,  116,  160,  148,  145,
      117,  149,  156,  106,  107,  157,  108,  150,  109,  166,
      170,  173,  167,  182,  184,  168,  169,  174,  194,  197,
      185,  171,  199,  205,  207,  282,  213,  183,  187,  195,
      563,  206,  214,  188,  189,  216,  217,  198,  200,  190,
      272,  215,  124,  208,  283,  191,  192,  209,  219,  127,

      291,  220,  128,  125,  238,  239,  257,  275,  273,  258,
      276,  286,  287,  293,  308,  330,  292,  336,  362,  344,
      337,  379,  309,  345,  294,  388,  427,  331,  363,  557,
      389,  562,  380,  561,  428,  390,  391,  560,  559,  556,
      555,  554,  553,  552,  551,  550,  558,   10,   10,   10,
       45,   45,   45,   50,   50,   50,   56,   56,  123,  123,
      123,  126,  126,  126,  129,  129,  132,  132,  549,  548,
      547,  546,  545,  544,  543,  542,  541,  540,  539,  538,
      537,  536,  535,  534,  533,  532,  531,  530,  529,  528,
      527,  526,  525,  524,  523,  522,  521,  520,  519,  518,

      517,  516,  515,  514,  513,  512,  511,  510,  509,  508,
      507,  506,  505,  504,  503,  502,  501,  500,  499,  498,
      497,  496,  495,  494,  493,  492,  491,  490,  489,  488,
      487,  486,  485,  484,  483,  482,  481,  480,  479,  478,
      477,  476,  475,  474,  473,  472,  471,  470,  469,  468,
      467,  466,  465,  464,  463,  462,  461,  460,  459,  458,
      457,  456,  455,  454,  453,  452,  451,  450,  449,  448,
      447,  446,  445,  444,  443,  442,  441,  440,  439,  438,
      437,  436,  435,  434,  433,  432,  431,  430,  429,  426,
      425,  424,  423,  422,  421,  420,  419,  418,  417,  416,

      415,  414,  413,  412,  411,  410,  409,  408,  407,  406,
      405,  404,  403,  402,  401,  400,  399,  398,  397,  396,
      395,  394,  393,  392,  387,  386,  385,  384,  383,  382,
      381,  378,  377,  376,  375,  374,  373,  372,  371,  370,
      369,  368,  367,  366,  365,  364,  361,  360,  359,  358,
      357,  356,  355,  354,  353,  352,  351,  350,  349,  348,
      347,  346,  343,  342,  341,  340,  339,  338,  335,  334,
      333,  332,  329,  328,  327,  326,  325,  324,  323,  322,
      321,  320,  319,  318,  317,  316,  315,  314,  313,  312,
      311,  310,  307,  306,  305,  304,  303,  302,  301,  300,

      299,  298,  297,  296,  295,  290,  289,  288,  285,  284,
      281,  280,  279,  278,  277,  274,  271,  270,  269,  268,
      267,  266,  265,  264,  263,  262,  261,  260,  259,  256,
      255,  254,  253,  252,  251,  250,  249,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  237,  236,  235,  234,
      233,  232,  231,  230,  229,  228,  227,  226,  225,  224,
      223,  568,  568,  222,  221,  218,  212,  211,  210,  204,
      203,  202,  201,  196,  193,  186,  181,  180,  179,  176,
      175,  172,  165,  164,  163,  162,  161,  158,  155,  154,
      153,  152,  151,  147,  146,  141,  140,  139,  138,  137,

      136,  135,  134,  133,  568,  568,  122,  121,  120,  101,
       89,   88,   82,   49,  568,    9,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568
    } ;

static yyconst short int yy_chk[656] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
      573,    3,   11,   37,    3,    3,    4,    5,    4,   37,
        5,    4,    4,   11,    6,    5,    5,    6,    7,    7,
      571,    7,    6,    6,   14,   32,    7,    7,    8,    8,
       20,    8,   14,   15,   15,   21,    8,    8,   49,   49,
      566,   32,   20,   22,   32,   23,   20,   20,   20,   21,
       22,   21,   30,  564,   22,   23,   30,   22,   21,   24,

       30,   24,   44,   25,   23,   44,   30,   43,   24,   35,
       24,   25,   35,   27,   25,   27,   31,   25,   43,   25,
       93,   35,   27,   27,   50,   93,   45,   27,   35,   66,
       66,   31,   50,  563,   31,   31,   34,   45,   78,   34,
      562,   36,   34,   34,   36,   67,   36,   78,   70,   67,
       36,   70,   76,   34,   34,   76,   34,   70,   34,   86,
       88,   90,   86,   98,   99,   86,   86,   90,  103,  105,
       99,   88,  106,  111,  112,  192,  116,   98,  101,  103,
      561,  111,  116,  101,  101,  117,  117,  105,  106,  101,
      183,  116,  123,  112,  192,  101,  101,  112,  119,  126,

      199,  119,  126,  123,  147,  147,  165,  185,  183,  165,
      185,  195,  195,  200,  215,  242,  199,  249,  276,  257,
      249,  293,  215,  257,  200,  303,  350,  242,  276,  547,
      303,  557,  293,  554,  350,  303,  303,  553,  548,  544,
      542,  540,  538,  532,  529,  528,  547,  569,  569,  569,
      570,  570,  570,  572,  572,  572,  574,  574,  575,  575,
      575,  576,  576,  576,  577,  577,  578,  578,  526,  525,
      523,  517,  515,  514,  513,  511,  510,  509,  508,  507,
      506,  505,  503,  502,  501,  500,  499,  495,  494,  493,
      491,  490,  489,  488,  487,  483,  481,  478,  475,  474,

      472,  471,  469,  467,  465,  463,  462,  460,  459,  455,
      453,  450,  446,  445,  444,  443,  441,  440,  439,  438,
      437,  435,  434,  432,  430,  429,  428,  427,  426,  423,
      422,  420,  419,  417,  416,  415,  412,  411,  410,  409,
      408,  407,  404,  403,  402,  400,  399,  397,  396,  395,
      393,  391,  390,  389,  388,  387,  386,  385,  384,  383,
      381,  380,  379,  378,  377,  376,  375,  373,  372,  370,
      369,  368,  367,  366,  365,  364,  363,  362,  361,  360,
      359,  358,  357,  356,  355,  354,  353,  352,  351,  349,
      347,  346,  345,  344,  343,  342,  339,  337,  336,  335,

      333,  332,  331,  330,  329,  328,  327,  324,  321,  320,
      319,  318,  317,  316,  315,  314,  312,  311,  310,  309,
      308,  307,  306,  305,  301,  300,  298,  297,  296,  295,
      294,  292,  291,  290,  289,  288,  286,  285,  284,  283,
      282,  281,  280,  279,  278,  277,  275,  274,  273,  272,
      271,  270,  269,  268,  267,  266,  265,  262,  261,  260,
      259,  258,  255,  254,  253,  252,  251,  250,  248,  247,
      244,  243,  241,  240,  239,  238,  237,  236,  234,  231,
      230,  227,  226,  225,  224,  223,  221,  220,  219,  218,
      217,  216,  214,  213,  212,  211,  210,  208,  207,  206,

      205,  204,  203,  202,  201,  198,  197,  196,  194,  193,
      191,  190,  189,  187,  186,  184,  182,  181,  179,  177,
      174,  173,  172,  171,  170,  169,  168,  167,  166,  164,
      163,  162,  161,  160,  159,  158,  157,  156,  155,  154,
      153,  152,  151,  150,  149,  148,  146,  145,  144,  143,
      142,  141,  140,  139,  138,  137,  136,  135,  133,  131,
      130,  128,  125,  121,  120,  118,  115,  114,  113,  110,
      109,  108,  107,  104,  102,  100,   97,   96,   94,   92,
       91,   89,   85,   82,   81,   80,   79,   77,   75,   74,
       73,   72,   71,   69,   68,   65,   64,   63,   62,   61,

       60,   59,   58,   57,   52,   47,   40,   39,   38,   33,
       29,   28,   26,   12,    9,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568
    } ;

#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define INITIAL 0
/**
 **********************************************************************
 * Copyright (c) 1988-2008 $organization$.
 *
 * This software is provided by the author and contributors ``as is'' and
 * any express or implied warranties, including, but not limited to, the
 * implied warranties of merchantability and fitness for a particular purpose
 * are disclaimed.  In no event shall the author or contributors be liable
 * for any direct, indirect, incidental, special, exemplary, or consequential
 * damages (including, but not limited to, procurement of substitute goods
 * or services; loss of use, data, or profits; or business interruption)
 * however caused and on any theory of liability, whether in contract, strict
 * liability, or tort (including negligence or otherwise) arising in any way
 * out of the use of this software, even if advised of the possibility of
 * such damage.
 *
 *   File: ccxxlex.l
 *
 * Author: $author$
 *   Date: 5/1/2008
 **********************************************************************
 */
#include "ccxxlexer.hxx"
#define XXSwitch(on, text, token) on(text, token); OnSwitch(text, token)
#define XXPush(on, text, token) on(text, token); OnPush(text, token)
#define XXPop(on, text, token) on(text, token); OnPop(text, token)
#define XX(on, text, token) on(text, token)
#define COMMENT 1
#define COMMENTLN 2
#define INCLUDE 3


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef yyLexer
#include "yylexer.hxx"
#endif

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif


#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#endif

#ifndef YY_NO_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_SWITCH_STATE
static void yy_switch_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
#define ECHO yy_lexer_output( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
    if ( (result = yy_lexer_input( (char *) buf, max_size )) < 0 ) \
        YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_lexer_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yyLexer::yylex()
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
    {
    register yy_state_type yy_current_state;
    register char *yy_cp, *yy_bp;
    register int yy_act;




    if ( yy_init )
        {
        yy_init = 0;

#ifdef YY_USER_INIT
        YY_USER_INIT;
#endif

        if ( ! yy_start )
            yy_start = 1;    /* first start state */

        if ( ! yyin )
            return EOF;

        if ( ! yyout )
            {
            YY_FATAL_ERROR("No output stream specified");
            return EOF;
            };

        if ( ! yy_current_buffer )
            yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

        yy_load_buffer_state();
        }

    while ( 1 )        /* loops until end-of-file is reached */
        {
        yy_cp = yy_c_buf_p;

        /* Support of yytext. */
        *yy_cp = yy_hold_char;

        /* yy_bp points to the position in yy_ch_buf of the start of
         * the current run.
         */
        yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 569 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 616 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

        YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:    /* This label is used only to access EOF actions. */


        switch ( yy_act )
    { /* beginning of action switch */

case 1:
YY_RULE_SETUP
{ XXPush(OnBeginComment, yytext, COMMENT); }
	YY_BREAK
case 2:
YY_RULE_SETUP
{ XXPush(OnBeginCommentLN, yytext, COMMENTLN); }
	YY_BREAK
case 3:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 4:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 5:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 6:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 7:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 8:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 9:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 10:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 11:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 12:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 13:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 14:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 15:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 16:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 17:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 18:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 19:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 20:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 21:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 22:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 23:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 24:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 25:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 26:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 27:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 28:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 29:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 30:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 31:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 32:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 33:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 34:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 35:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 36:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 37:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 38:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 39:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 40:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 41:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 42:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 43:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 44:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 45:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 46:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 47:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 48:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 49:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 50:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 51:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 52:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 53:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 54:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 55:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 56:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 57:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 58:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 59:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 60:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 61:
YY_RULE_SETUP
{ XX(OnReserved, yytext, 0); }
	YY_BREAK
case 62:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 63:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 64:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 65:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 66:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 67:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 68:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 69:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 70:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 71:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 72:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 73:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 74:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 75:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 76:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 77:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 78:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 79:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 80:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 81:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 82:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 83:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 84:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 85:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 86:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 87:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 88:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 89:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 90:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 91:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 92:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 93:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 94:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 95:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 96:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 97:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 98:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 99:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 100:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 101:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 102:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 103:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 104:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 105:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 106:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 107:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 108:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 109:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 110:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 111:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 112:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 113:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 114:
YY_RULE_SETUP
{ XX(OnReservedX, yytext, 0); }
	YY_BREAK
case 115:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 116:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 117:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 118:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 119:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 120:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 121:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 122:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 123:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 124:
YY_RULE_SETUP
{ XX(OnReservedY, yytext, 0); }
	YY_BREAK
case 125:
YY_RULE_SETUP
{ XX(OnString, yytext, 0); }
	YY_BREAK
case 126:
YY_RULE_SETUP
{ XX(OnChar, yytext, 0); }
	YY_BREAK
case 127:
YY_RULE_SETUP
{ XXPush(OnProcessor, yytext, INCLUDE); }
	YY_BREAK
case 128:
YY_RULE_SETUP
{ XXPush(OnProcessor, yytext, INCLUDE); }
	YY_BREAK
case 129:
YY_RULE_SETUP
{ XX(OnProcessor, yytext, 0); }
	YY_BREAK
case 130:
YY_RULE_SETUP
{ XX(OnProcessor, yytext, 0); }
	YY_BREAK
case 131:
YY_RULE_SETUP
{ XX(OnText, yytext, 0); }
	YY_BREAK


case 132:
YY_RULE_SETUP
{ XX(OnIncludeL, yytext, 0); }
	YY_BREAK
case 133:
YY_RULE_SETUP
{ XX(OnIncludeL, yytext, 0); }
	YY_BREAK
case 134:
YY_RULE_SETUP
{ XXPop(OnText, yytext, INCLUDE);}
	YY_BREAK


case 135:
YY_RULE_SETUP
{ XXPop(OnEndComment, yytext, COMMENT);}
	YY_BREAK


case 136:
YY_RULE_SETUP
{ XXPop(OnEndCommentLN, yytext, COMMENTLN);}
	YY_BREAK


case 137:
YY_RULE_SETUP
{ XX(OnLT, yytext, 0);}
	YY_BREAK
case 138:
YY_RULE_SETUP
{ XX(OnGT, yytext, 0);}
	YY_BREAK
case 139:
YY_RULE_SETUP
{ XX(OnAMP, yytext, 0);}
	YY_BREAK
case 140:
YY_RULE_SETUP
{ XX(OnText, yytext, 0);}
	YY_BREAK

case 141:
YY_RULE_SETUP
ECHO;
	YY_BREAK
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(COMMENT):
			case YY_STATE_EOF(COMMENTLN):
			case YY_STATE_EOF(INCLUDE):
				yyterminate();

    case YY_END_OF_BUFFER:
        {
        /* Amount of text matched not including the EOB char. */
        int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

        /* Undo the effects of YY_DO_BEFORE_ACTION. */
        *yy_cp = yy_hold_char;

        if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
            {
            /* We're scanning a new file or input source.  It's
             * possible that this happened because the user
             * just pointed yyin at a new source and called
             * yylex().  If so, then we have to assure
             * consistency between yy_current_buffer and our
             * globals.  Here is the right place to do so, because
             * this is the first action (other than possibly a
             * back-up) that will match for the new input source.
             */
            yy_n_chars = yy_current_buffer->yy_n_chars;
            yy_current_buffer->yy_input_file = yyin;
            yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
            }

        /* Note that here we test for yy_c_buf_p "<=" to the position
         * of the first EOB in the buffer, since yy_c_buf_p will
         * already have been incremented past the NUL character
         * (since all states make transitions on EOB to the
         * end-of-buffer state).  Contrast this with the test
         * in input().
         */
        if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
            { /* This was really a NUL. */
            yy_state_type yy_next_state;

            yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

            yy_current_state = yy_get_previous_state();

            /* Okay, we're now positioned to make the NUL
             * transition.  We couldn't have
             * yy_get_previous_state() go ahead and do it
             * for us because it doesn't know how to deal
             * with the possibility of jamming (and we don't
             * want to build jamming into it because then it
             * will run more slowly).
             */

            yy_next_state = yy_try_NUL_trans( yy_current_state );

            yy_bp = yytext_ptr + YY_MORE_ADJ;

            if ( yy_next_state )
                {
                /* Consume the NUL. */
                yy_cp = ++yy_c_buf_p;
                yy_current_state = yy_next_state;
                goto yy_match;
                }

            else
                {
				yy_cp = yy_c_buf_p;
                goto yy_find_action;
                }
            }

        else switch ( yy_get_next_buffer() )
            {
            case EOB_ACT_END_OF_FILE:
                {
                yy_did_buffer_switch_on_eof = 0;

                if ( yywrap() )
                    {
                    /* Note: because we've taken care in
                     * yy_get_next_buffer() to have set up
                     * yytext, we can now set up
                     * yy_c_buf_p so that if some total
                     * hoser (like flex itself) wants to
                     * call the scanner after we return the
                     * YY_NULL, it'll still work - another
                     * YY_NULL will get returned.
                     */
                    yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

                    yy_act = YY_STATE_EOF(YY_START);
                    goto do_action;
                    }

                else
                    {
                    if ( ! yy_did_buffer_switch_on_eof )
                        YY_NEW_FILE;
                    }
                break;
                }

            case EOB_ACT_CONTINUE_SCAN:
                yy_c_buf_p =
                    yytext_ptr + yy_amount_of_matched_text;

                yy_current_state = yy_get_previous_state();

                yy_cp = yy_c_buf_p;
                yy_bp = yytext_ptr + YY_MORE_ADJ;
                goto yy_match;

            case EOB_ACT_LAST_MATCH:
                yy_c_buf_p =
                &yy_current_buffer->yy_ch_buf[yy_n_chars];

                yy_current_state = yy_get_previous_state();

                yy_cp = yy_c_buf_p;
                yy_bp = yytext_ptr + YY_MORE_ADJ;
                goto yy_find_action;
            }
        break;
        }

    default:
        YY_FATAL_ERROR(
            "fatal flex scanner internal error--no action found" );
    } /* end of action switch */
        } /* end of scanning one token */
    } /* end of yylex */

int yyIsLexer::yyprintf( const char* format, ... )
    {
    va_list arg;
    int result;

    va_start(arg,format);
    result=vprintf(format,arg);
    va_end(arg);
    return result;
    }

int yyIsLexer::yywrap()
    {
    return 1;
    }

yyIsLexer::yyIsLexer(cCharStreamInterface &out, cCharStreamInterface &in)
    : m_out(out),
      m_in(in)
    {
    yy_initialize();
    yyin = &in;
    yyout = &out;
    }

yyIsLexer::~yyIsLexer()
    {
    yy_finish();
    }

#ifdef YY_INTERACTIVE
int yyIsLexer::yy_lexer_input( char* buf, int /* max_size */ )
#else
int yyIsLexer::yy_lexer_input( char* buf, int max_size )
#endif
    {
    int count;
#ifdef YY_INTERACTIVE
    char c;

    if ((count=yyin->Get(c)) < 0)
        return 0;

    buf[0]=c;
#else

    if ((count=yyin->Read(buf, max_size )) < 0)
        return 0;
#endif

    return count;
    }

void yyIsLexer::yy_lexer_output( const char* buf, int size )
    {
    yyout->Write(buf, size );
    }


void yyIsLexer::yy_initialize( void )
    {
    yyin = 0;
    yyout = 0;
    yy_c_buf_p = 0;
    yy_init = 1;
    yy_start = 0;
    yy_did_buffer_switch_on_eof = 0;
    yy_start_stack_ptr = 0;
    yy_start_stack_depth = 0;
    yy_start_stack = 0;
    yy_current_buffer = 0;
    yylineno = 1;    /* this will only get updated if %option yylineno */
    yy_flex_debug = 0;
    yy_looking_for_trail_begin = 0;
    yy_more_flag = 0;
    yy_more_len = 0;

#ifdef YY_USES_REJECT
    yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
    yy_state_buf = 0;
#endif
    }


void yyIsLexer::yy_finish( void )
    {
    delete yy_state_buf;
    yy_delete_buffer( yy_current_buffer );
    }


void yyIsLexer::yy_reset( void )
    {
    yy_finish();
    yy_initialize();
    }


void *yyIsLexer::yy_save_scan_state( cCharStreamInterface *input_file )
    {
    YY_BUFFER_STATE old_state,new_state;

    if ((old_state=yy_current_buffer))
		old_state->yy_lineno = yylineno;

    if ((new_state=yy_create_buffer(input_file,YY_BUF_SIZE))!=0)
        yy_switch_to_buffer(new_state);

    yylineno = 1;

    return old_state;
    }


void yyIsLexer::yy_restore_scan_state( void *old_state )
    {
    YY_BUFFER_STATE current_state;
    YY_BUFFER_STATE previous_state;

    current_state=yy_current_buffer;

    yy_switch_to_buffer(previous_state=(YY_BUFFER_STATE)old_state);
    yylineno = previous_state->yy_lineno;

    if (current_state)
        yy_delete_buffer(current_state);
    }


void yyIsLexer::yy_switch_streams( cCharStreamInterface* new_in, cCharStreamInterface* new_out )
    {
    if ( new_in )
        {
        yy_delete_buffer( yy_current_buffer );
        yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
        }

    if ( new_out )
        yyout = new_out;
    }

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *    EOB_ACT_LAST_MATCH -
 *    EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *    EOB_ACT_END_OF_FILE - end of file
 */

int yyIsLexer::yy_get_next_buffer()
    {
    register char *dest = yy_current_buffer->yy_ch_buf;
    register char *source = yytext_ptr;
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
        YY_FATAL_ERROR(
        "fatal flex scanner internal error--end of buffer missed" );

    if ( yy_current_buffer->yy_fill_buffer == 0 )
        { /* Don't try to fill the buffer, so this is an EOF. */
        if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
            {
            /* We matched a singled characater, the EOB, so
             * treat this as a final EOF.
             */
            return EOB_ACT_END_OF_FILE;
            }

        else
            {
            /* We matched some text prior to the EOB, first
             * process it.
             */
            return EOB_ACT_LAST_MATCH;
            }
        }

    /* Try to read more data. */

    /* First move last chars to start of buffer. */
    number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

    for ( i = 0; i < number_to_move; ++i )
        *(dest++) = *(source++);

    if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
        /* don't do the read, it's not guaranteed to return an EOF,
         * just force an EOF
         */
        yy_n_chars = 0;

    else
        {
        int num_to_read =
            yy_current_buffer->yy_buf_size - number_to_move - 1;

        while ( num_to_read <= 0 )
            { /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
            YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

            /* just a shorter name for the current buffer */
            YY_BUFFER_STATE b = yy_current_buffer;

            int yy_c_buf_p_offset =
                (int) (yy_c_buf_p - b->yy_ch_buf);

            if ( b->yy_is_our_buffer )
                {
                int new_size = b->yy_buf_size * 2;

                if ( new_size <= 0 )
                    b->yy_buf_size += b->yy_buf_size / 8;
                else
                    b->yy_buf_size *= 2;

                b->yy_ch_buf = (char *)
                    /* Include room in for 2 EOB chars. */
                    yy_flex_realloc( (void *) b->yy_ch_buf,
                             b->yy_buf_size + 2 );
                }
            else
                /* Can't grow it, we don't own it. */
                b->yy_ch_buf = 0;

            if ( ! b->yy_ch_buf )
                YY_FATAL_ERROR(
                "fatal error - scanner input buffer overflow" );

            yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

            num_to_read = yy_current_buffer->yy_buf_size -
                        number_to_move - 1;
#endif
            }

        if ( num_to_read > YY_READ_BUF_SIZE )
            num_to_read = YY_READ_BUF_SIZE;

        /* Read in more data. */
        YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
            yy_n_chars, num_to_read );
        }

    if ( yy_n_chars == 0 )
        {
        if ( number_to_move == YY_MORE_ADJ )
            {
            ret_val = EOB_ACT_END_OF_FILE;
            yyrestart( yyin );
            }

        else
            {
            ret_val = EOB_ACT_LAST_MATCH;
            yy_current_buffer->yy_buffer_status =
                YY_BUFFER_EOF_PENDING;
            }
        }

    else
        ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

    return ret_val;
    }


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyIsLexer::yy_get_previous_state()
    {
    register yy_state_type yy_current_state;
    register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

    for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
        {
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 569 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
        }

    return yy_current_state;
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *    next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyIsLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
    {
    register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 569 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	*yy_state_ptr++ = yy_current_state;
	yy_is_jam = (yy_current_state == 568);

    return yy_is_jam ? 0 : yy_current_state;
    }


void yyIsLexer::yyunput( int c, register char* yy_bp )
    {
    register char *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
        { /* need to shift things up to make room */
        /* +2 for EOB chars. */
        register int number_to_move = yy_n_chars + 2;
        register char *dest = &yy_current_buffer->yy_ch_buf[
                    yy_current_buffer->yy_buf_size + 2];
        register char *source =
                &yy_current_buffer->yy_ch_buf[number_to_move];

        while ( source > yy_current_buffer->yy_ch_buf )
            *--dest = *--source;

        yy_cp += (int) (dest - source);
        yy_bp += (int) (dest - source);
        yy_n_chars = yy_current_buffer->yy_buf_size;

        if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
            YY_FATAL_ERROR( "flex scanner push-back overflow" );
        }

    *--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

    yytext_ptr = yy_bp;
    yy_hold_char = *yy_cp;
    yy_c_buf_p = yy_cp;
    }


int yyIsLexer::yyinput()
    {
    int c;

    *yy_c_buf_p = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
        {
        /* yy_c_buf_p now points to the character we want to return.
         * If this occurs *before* the EOB characters, then it's a
         * valid NUL; if not, then we've hit the end of the buffer.
         */
        if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
            /* This was really a NUL. */
            *yy_c_buf_p = '\0';

        else
            { /* need more input */
            yytext_ptr = yy_c_buf_p;
            ++yy_c_buf_p;

            switch ( yy_get_next_buffer() )
                {
                case EOB_ACT_END_OF_FILE:
                    {
                    if ( yywrap() )
                        {
                        yy_c_buf_p =
                        yytext_ptr + YY_MORE_ADJ;
                        return EOF;
                        }

                    if ( ! yy_did_buffer_switch_on_eof )
                        YY_NEW_FILE;
#ifdef __cplusplus
                    return yyinput();
#else
                    return input();
#endif
                    }

                case EOB_ACT_CONTINUE_SCAN:
                    yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
                    break;

                case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
                    YY_FATAL_ERROR(
                    "unexpected last match in yyinput()" );
#else
                    YY_FATAL_ERROR(
                    "unexpected last match in input()" );
#endif
                }
            }
        }

    c = *(unsigned char *) yy_c_buf_p;    /* cast for 8-bit char's */
    *yy_c_buf_p = '\0';    /* preserve yytext */
    yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

    return c;
    }


void yyIsLexer::yyrestart( cCharStreamInterface* input_file )
    {
    if ( ! yy_current_buffer )
        yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
    }


void yyIsLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
    {
    if ( yy_current_buffer == new_buffer )
        return;

    if ( yy_current_buffer )
        {
        /* Flush out information for old buffer. */
        *yy_c_buf_p = yy_hold_char;
        yy_current_buffer->yy_buf_pos = yy_c_buf_p;
        yy_current_buffer->yy_n_chars = yy_n_chars;
        }

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* We don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


void yyIsLexer::yy_load_buffer_state()
    {
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


YY_BUFFER_STATE yyIsLexer::yy_create_buffer( cCharStreamInterface* file, int size )
    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
    if ( ! b )
        YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
    if ( ! b->yy_ch_buf )
        YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_is_our_buffer = 1;

    yy_init_buffer( b, file );

    return b;
    }


void yyIsLexer::yy_delete_buffer( YY_BUFFER_STATE b )
    {
    if ( ! b )
        return;

    if ( b == yy_current_buffer )
        yy_current_buffer = (YY_BUFFER_STATE) 0;

    if ( b->yy_is_our_buffer )
        yy_flex_free( (void *) b->yy_ch_buf );

    yy_flex_free( (void *) b );
    }


void yyIsLexer::yy_init_buffer( YY_BUFFER_STATE b, cCharStreamInterface* file )

    {
    yy_flush_buffer( b );

    b->yy_input_file = file;
	b->yy_lineno = 1;
    b->yy_fill_buffer = 1;

    b->yy_is_interactive = 0;
    }


void yyIsLexer::yy_flush_buffer( YY_BUFFER_STATE b )
    {
    b->yy_n_chars = 0;

    /* We always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[0];

    b->yy_at_bol = 1;
    b->yy_buffer_status = YY_BUFFER_NEW;

    if ( b == yy_current_buffer )
        yy_load_buffer_state();
    }


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif


#ifndef YY_NO_SWITCH_STATE
void yyIsLexer::yy_switch_state( int new_state )
    {
    BEGIN(new_state);
    }
#endif


#ifndef YY_NO_PUSH_STATE
void yyIsLexer::yy_push_state( int new_state )
    {
    if ( yy_start_stack_ptr >= yy_start_stack_depth )
        {
        yy_size_t new_size;

        yy_start_stack_depth += YY_START_STACK_INCR;
        new_size = yy_start_stack_depth * sizeof( int );

        if ( ! yy_start_stack )
            yy_start_stack = (int *) yy_flex_alloc( new_size );

        else
            yy_start_stack = (int *) yy_flex_realloc(
                    (void *) yy_start_stack, new_size );

        if ( ! yy_start_stack )
            YY_FATAL_ERROR(
            "out of memory expanding start-condition stack" );
        }

    yy_start_stack[yy_start_stack_ptr++] = YY_START;

    BEGIN(new_state);
    }
#endif


#ifndef YY_NO_POP_STATE
void yyIsLexer::yy_pop_state()
    {
    if ( --yy_start_stack_ptr < 0 )
        YY_FATAL_ERROR( "start-condition stack underflow" );

    BEGIN(yy_start_stack[yy_start_stack_ptr]);
    }
#endif


#ifndef YY_NO_TOP_STATE
int yyIsLexer::yy_top_state()
    {
    return yy_start_stack[yy_start_stack_ptr - 1];
    }
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyIsLexer::yy_lexer_error( yyconst char *msg )
    {
    yyprintf("%s\n",msg);
    exit( YY_EXIT_FAILURE );
    }


/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
    do \
        { \
        /* Undo effects of setting up yytext. */ \
        yytext[yyleng] = yy_hold_char; \
        yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
        yy_hold_char = *yy_c_buf_p; \
        *yy_c_buf_p = '\0'; \
        yyleng = n; \
        } \
    while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
    {
    register int i;
    for ( i = 0; i < n; ++i )
        s1[i] = s2[i];
    }
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
    {
    return (void *) malloc( size );
    }

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
    {
    /* The cast to (char *) in the following accommodates both
     * implementations that use char* generic pointers, and those
     * that use void* generic pointers.  It works with the latter
     * because both ANSI C and C++ allow castless assignment from
     * any pointer type to void*, and deal with argument conversions
     * as though doing an assignment.
     */
    return (void *) realloc( (char *) ptr, size );
    }

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
    {
    free( ptr );
    }

#if YY_MAIN
int main()
    {
    yylex();
    return 0;
    }
#endif

